name: Meson and Ninja

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installing Meson and Ninja
      run: sudo apt update && sudo apt install -y python3-pip ninja-build && pip3 install --user meson

    - name: Installing GTKmm dependencies
      run: sudo apt-get install -y libgtk-4-dev libglibmm-2.4-dev libsigc++-2.0-dev libcairomm-1.1-dev libpangomm-2.2-dev
    
    - name: Setting up GTKmm
      run: |
        wget https://download.gnome.org/sources/gtkmm/4.10/gtkmm-4.10.0.tar.xz
        tar xf gtkmm-4.10.0.tar.xz
        cd gtkmm-4.10.0
        meson setup --libdir lib my_build .
        cd my_build/
        ninja
        ninja install
        cd ../../

    - name: Build
      run: meson build && cd build && ninja
