name: Meson and Ninja

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installing Meson and Ninja
      run: sudo apt update && sudo apt install -y python3-pip ninja-build && sudo pip3 install meson

    - name: Installing GTKmm dependencies
      run: |
        sudo apt install build-essential git g++ autotools-dev libgtkmm-3.0-dev \
         libgtkmm-3.0-doc mm-common libgtk-4-bin \
         libgtk-4-common libgtk-4-dev libgtk-4-doc pkg-config

        wget ftp://ftp.acc.umu.se/pub/gnome/sources/libsigc++/3.0/libsigc++-3.0.7.tar.xz
        tar xf libsigc++-3.0.7.tar.xz
        cd libsigc++-3.0.7
        meson --libdir lib --prefix=/usr/local my_build .
        cd my_build
        ninja
        sudo ninja install
        cd ../..

        wget https://download.gnome.org/sources/glibmm/2.68/glibmm-2.68.2.tar.xz
        tar xf glibmm-2.68.2.tar.xz
        meson --libdir lib --prefix=/usr my_build .
        cd my_build
        ninja
        ninja install
        cd ../..

        wget https://www.cairographics.org/releases/cairomm-1.16.2.tar.xz
        tar xf cairomm-1.16.2.tar.xz
        cd cairomm-1.16.2
        meson --libdir lib --prefix=/usr my_build .
        cd my_build
        ninja
        sudo ninja install
        cd ../..

        wget https://download.gnome.org/sources/pangomm/2.48/pangomm-2.48.0.tar.xz
        tar xf pangomm-2.48.0.tar.xz
        cd pangomm-2.48.0/
        meson --libdir lib --prefix=/usr my_build .
        cd my_build
        ninja
        sudo ninja install
        cd ../..
    
    - name: Setting up GTKmm
      run: |
        wget https://download.gnome.org/sources/gtkmm/4.10/gtkmm-4.10.0.tar.xz
        tar xf gtkmm-4.10.0.tar.xz
        cd gtkmm-4.10.0
        meson setup --libdir lib my_build .
        cd my_build/
        ninja
        sudo ninja install
        cd ../../

    - name: Build
      run: meson build && cd build && ninja
